# Generated by Django 2.1.2 on 2018-10-02 02:45

import depot.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('original', models.FileField(upload_to=depot.models.original_path)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='depot.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('num', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('data', models.FileField(upload_to=depot.models.resource_path)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='depot.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('mimetype', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alts', to='depot.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('players', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('address', 'port')},
        ),
        migrations.AddField(
            model_name='level',
            name='pict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='depot.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('collection', 'tag', 'num')},
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('collection', 'tag'), ('collection', 'slug')},
        ),
    ]
